name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Navigate to project directory and build with Maven
      run: |
        cd F-BJV24001115-synergy7-fir-binfud-ch6
        mvn clean install

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: jar-file
        path: F-BJV24001115-synergy7-fir-binfud-ch6/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: jar-file
        path: target/

    - name: Copy JAR to remote server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_PRIVATE_KEY }}
        source: "F-BJV24001115-synergy7-fir-binfud-ch6/target/*.jar"
        target: "/var/www/app.jar"

    - name: Restart application on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_PRIVATE_KEY }}
        script: |
          sudo systemctl stop binarfud.service
          sudo systemctl start binarfud.service
